name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Build
        run: |
          bun install
          bun run build
  test:
    runs-on: ubuntu-latest
    environment: Testing All Networks
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Start anvil node
        run: anvil &
      - name: Run tests
        env:
          SUBGRAPH_URL_ARBITRUM_ONE: ${{ secrets.SUBGRAPH_URL_ARBITRUM_ONE }}
          SUBGRAPH_URL_ARBITRUM_SEPOLIA: ${{ secrets.SUBGRAPH_URL_ARBITRUM_SEPOLIA }}
          SUBGRAPH_URL_BASE: ${{ secrets.SUBGRAPH_URL_BASE }}
          SUBGRAPH_URL_BASE_SEPOLIA: ${{ secrets.SUBGRAPH_URL_BASE_SEPOLIA }}
          SUBGRAPH_URL_HOLESKY: ${{ secrets.SUBGRAPH_URL_HOLESKY }}
          SUBGRAPH_URL_MAINNET: ${{ secrets.SUBGRAPH_URL_MAINNET }}
          SUBGRAPH_URL_MATIC: ${{ secrets.SUBGRAPH_URL_MATIC }}
          SUBGRAPH_URL_OPTIMISM: ${{ secrets.SUBGRAPH_URL_OPTIMISM }}
          SUBGRAPH_URL_OPTIMISM_SEPOLIA: ${{ secrets.SUBGRAPH_URL_OPTIMISM_SEPOLIA }}
          SUBGRAPH_URL_SEPOLIA: ${{ secrets.SUBGRAPH_URL_SEPOLIA }}
        run: |
          bun install
          bun test
  coverage:
    runs-on: ubuntu-latest
    environment: Testing All Networks
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Start anvil node
        run: anvil &
      - name: Run test coverage
        env:
          SUBGRAPH_URL_ARBITRUM_ONE: ${{ secrets.SUBGRAPH_URL_ARBITRUM_ONE }}
          SUBGRAPH_URL_ARBITRUM_SEPOLIA: ${{ secrets.SUBGRAPH_URL_ARBITRUM_SEPOLIA }}
          SUBGRAPH_URL_BASE: ${{ secrets.SUBGRAPH_URL_BASE }}
          SUBGRAPH_URL_BASE_SEPOLIA: ${{ secrets.SUBGRAPH_URL_BASE_SEPOLIA }}
          SUBGRAPH_URL_HOLESKY: ${{ secrets.SUBGRAPH_URL_HOLESKY }}
          SUBGRAPH_URL_MAINNET: ${{ secrets.SUBGRAPH_URL_MAINNET }}
          SUBGRAPH_URL_MATIC: ${{ secrets.SUBGRAPH_URL_MATIC }}
          SUBGRAPH_URL_OPTIMISM: ${{ secrets.SUBGRAPH_URL_OPTIMISM }}
          SUBGRAPH_URL_OPTIMISM_SEPOLIA: ${{ secrets.SUBGRAPH_URL_OPTIMISM_SEPOLIA }}
          SUBGRAPH_URL_SEPOLIA: ${{ secrets.SUBGRAPH_URL_SEPOLIA }}
        run: |
          bun install
          bun test --coverage
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
      - name: Check
        run: |
          bun install
          bun run check
